//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int Id_friendship { get; set; }
        public int Id_user1 { get; set; }
        public int Id_user2 { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
