//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id_message { get; set; }
        public int Id_userFrom { get; set; }
        public int Id_userTo { get; set; }
        public string Content { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
